### ISSUE TITLE
Errors when running -> flipped conditions and wrong "exit 0"?

### ISSUE THREAD

**Issue by jakobkilian** [gougeon-s/fp3_flash_stock#1]
I am no pro at all (!), sorry If I got something wrong. 

1. When running the script It directly prompted 

> "Couldn't find ./product.img"

As the file actually was there, I looked in the script and found this:
`[ -f product.img ] && _exit "Couldn't find ./product.img"`

But that should mean: IF the file is there DO exit...
With this it works for me:
`[ ! -f product.img ] && _exit "Couldn't find ./product.img"`

2. Furthermore I do not understand the use of the `exit 0` in line 45. Won't it always be executed?

3. It always ends with 

> Couldn't reboot to slot $FLASH_SLOT

Maybe 'cause the phone is still rebooting?

best, Janos

**Comment by p1gp1g** [comment]
You're right I did this two things to do some tests but I have forgotten it. Even without these mistakes you have the third error? If so, I'll add a `fastboot devices` to wait for the end of the reboot

**Comment by jakobkilian** [comment]
Thanks, perfect.
Weird thing is, It just happens on one slot.. Maybe waiting for `fastboot devices`makes sense. I mean is there a downside of waiting for it..?

**Comment by p1gp1g** [comment]
`fastboot device` can't do anything wrong but it is useless if we can get rid of it. Are you sure that you have a working bootloader on both slots? 
```
fastboot --set-active=a
fastboot reboot bootloader
fastboot getvar current-slot 2>&1 | grep "current-slot: a" || echo "a not working"
fastboot --set-active=b
fastboot reboot bootloader
fastboot getvar current-slot 2>&1 | grep "current-slot: b" || echo "b not working"
```

**Comment by jakobkilian** [comment]
Yes, I can ensure, that both bootloaders work.
I tried to reproduce the error, but it didn't occur again. So jeah, maybe leave it, as it is...  :-)
